<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="2" failures="0" hostname="liqingMacBook-Pro.local" name="pytest" skipped="0" tests="2" time="25.213" timestamp="2020-03-25T19:34:34.341312"><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="23" name="test_weather_desc_equal" time="19.069"><error message="test setup failure">self = &lt;test_case.test_weather_condition.TestWeatherCondition object at 0x109c32828&gt;

    def setup(self):
&gt;       self.driver.launch_app()
E       AttributeError: &apos;TestWeatherCondition&apos; object has no attribute &apos;driver&apos;

test_case/test_weather_condition.py:18: AttributeError</error></testcase><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="27" name="test_temp_equal" time="0.002"><error message="test setup failure">self = &lt;test_case.test_weather_condition.TestWeatherCondition object at 0x109c34f28&gt;

    def setup(self):
&gt;       self.driver.launch_app()
E       AttributeError: &apos;TestWeatherCondition&apos; object has no attribute &apos;driver&apos;

test_case/test_weather_condition.py:18: AttributeError</error></testcase></testsuite></testsuites>