<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="liqingMacBook-Pro.local" name="pytest" skipped="0" tests="2" time="54.745" timestamp="2020-03-25T23:36:38.052447"><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="27" name="test_weather_desc_equal" time="27.655"></testcase><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="37" name="test_temp_equal" time="22.110"><failure message="assert False">self = &lt;test_case.test_weather_condition.TestWeatherCondition object at 0x109c8aeb8&gt;
browser = &lt;appium.webdriver.webdriver.WebDriver (session=&quot;e6fabcb4-8863-4c40-9726-20ca0638a7b0&quot;)&gt;

    @pytest.mark.flaky(reruns=1, reruns_delay=1)
    def test_temp_equal(self, browser):
        self.weather_condition_business = WeatherCompareBusiness(browser)
        result = self.weather_condition_business.compare_temp()
&gt;       assert result
E       assert False

test_case/test_weather_condition.py:42: AssertionError</failure></testcase></testsuite></testsuites>