<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="liqingMacBook-Pro.local" name="pytest" skipped="0" tests="2" time="80.821" timestamp="2020-03-25T19:59:08.271829"><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="24" name="test_weather_desc_equal" time="39.508"></testcase><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="30" name="test_temp_equal" time="37.457"><failure message="assert False">self = &lt;test_case.test_weather_condition.TestWeatherCondition object at 0x109a55358&gt;
browser = &lt;appium.webdriver.webdriver.WebDriver (session=&quot;76a35384-e3c3-4b9f-9b78-f377566bc927&quot;)&gt;

    def test_temp_equal(self, browser):
        browser.launch_app()
        self.weather_condition_business = WeatherCompareBusiness(browser)
        result = self.weather_condition_business.compare_temp()
        print(&quot;result&quot;, result)
&gt;       assert result
E       assert False

test_case/test_weather_condition.py:36: AssertionError</failure></testcase></testsuite></testsuites>