<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="2" failures="0" hostname="liqingMacBook-Pro.local" name="pytest" skipped="0" tests="2" time="24.915" timestamp="2020-03-25T19:48:30.193021"><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="24" name="test_weather_desc_equal" time="19.096"><error message="test setup failure">self = &lt;test_case.test_weather_condition.TestWeatherCondition object at 0x109c2a860&gt;

    def setup(self):
&gt;       self.driver.launch_app()
E       AttributeError: &apos;TestWeatherCondition&apos; object has no attribute &apos;driver&apos;

common/all_test.py:27: AttributeError</error></testcase><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="30" name="test_temp_equal" time="0.002"><error message="test setup failure">self = &lt;test_case.test_weather_condition.TestWeatherCondition object at 0x109c3bd30&gt;

    def setup(self):
&gt;       self.driver.launch_app()
E       AttributeError: &apos;TestWeatherCondition&apos; object has no attribute &apos;driver&apos;

common/all_test.py:27: AttributeError</error></testcase></testsuite></testsuites>